package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author José
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        inserirIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnBase = new javax.swing.JPanel();
        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblPerfilUser = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadUserFull = new javax.swing.JMenuItem();
        menCadProd = new javax.swing.JMenuItem();
        menHelp = new javax.swing.JMenu();
        menHelpSobre = new javax.swing.JMenuItem();
        menOption = new javax.swing.JMenu();
        menOptionSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDRL Materiais de Construção - Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        JpnBase.setBackground(new java.awt.Color(255, 255, 255));
        JpnBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 60, 0), 5));
        JpnBase.setMinimumSize(new java.awt.Dimension(917, 590));
        JpnBase.setPreferredSize(new java.awt.Dimension(917, 590));
        JpnBase.setRequestFocusEnabled(false);
        JpnBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktop.setBackground(new java.awt.Color(0, 68, 111));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        JpnBase.add(desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, 608));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background_246X235.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(248, 239));
        jLabel1.setMinimumSize(new java.awt.Dimension(248, 239));
        jLabel1.setPreferredSize(new java.awt.Dimension(248, 239));
        JpnBase.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 260, 240, 239));

        lblPerfilUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPerfilUser.setText("Perfil");
        JpnBase.add(lblPerfilUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, 30));

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblData.setText("Data");
        JpnBase.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");
        lblUsuario.setMaximumSize(new java.awt.Dimension(225, 25));
        JpnBase.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 225, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 68, 111));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><center>IDRL Materiais</br> de Construção</center></html>");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JpnBase.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 15, 236, 70));

        jSeparator2.setForeground(new java.awt.Color(255, 60, 0));
        JpnBase.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 100, 240, -1));

        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 60, 0), 5));

        menCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu_cadastro_48X48.png"))); // NOI18N
        menCad.setText("Cadastro");
        menCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menCad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menCad.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menCad.setMinimumSize(new java.awt.Dimension(135, 64));
        menCad.setPreferredSize(new java.awt.Dimension(135, 64));

        menCadUserFull.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadUserFull.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        menCadUserFull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu_cad_user_32X32.png"))); // NOI18N
        menCadUserFull.setText("Usuário");
        menCadUserFull.setEnabled(false);
        menCadUserFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUserFullActionPerformed(evt);
            }
        });
        menCad.add(menCadUserFull);

        menCadProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadProd.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        menCadProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu_cad_prod_32X32.png"))); // NOI18N
        menCadProd.setText("Produto");
        menCadProd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menCadProd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menCadProd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        menCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadProdActionPerformed(evt);
            }
        });
        menCad.add(menCadProd);

        Menu.add(menCad);

        menHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu_ajuda_48X48.png"))); // NOI18N
        menHelp.setText("Ajuda");
        menHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menHelp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        menHelpSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menHelpSobre.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        menHelpSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu_ajuda_sobre_32X32.png"))); // NOI18N
        menHelpSobre.setText("Sobre");
        menHelpSobre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menHelpSobre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menHelpSobre.setMargin(new java.awt.Insets(2, 2, 2, 2));
        menHelpSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menHelpSobreActionPerformed(evt);
            }
        });
        menHelp.add(menHelpSobre);

        Menu.add(menHelp);

        menOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu_opcoes_48X48.png"))); // NOI18N
        menOption.setText("Opções");
        menOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menOption.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menOption.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menOption.setMargin(new java.awt.Insets(2, 2, 0, 2));

        menOptionSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menOptionSair.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        menOptionSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu_opcoes_sair_32X32.png"))); // NOI18N
        menOptionSair.setText("Sair");
        menOptionSair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menOptionSair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menOptionSair.setMargin(new java.awt.Insets(2, 2, 2, 2));
        menOptionSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOptionSairActionPerformed(evt);
            }
        });
        menOption.add(menOptionSair);

        Menu.add(menOption);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnBase, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(994, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menHelpSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menHelpSobreActionPerformed
        menuSobre();
    }//GEN-LAST:event_menHelpSobreActionPerformed

    private void menOptionSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOptionSairActionPerformed
        btnSairTelaPrincipal();
    }//GEN-LAST:event_menOptionSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        insereData();
    }//GEN-LAST:event_formWindowActivated

    private void menCadUserFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUserFullActionPerformed
       menCadUserFull();
    }//GEN-LAST:event_menCadUserFullActionPerformed

    private void menCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadProdActionPerformed
        menCadProdFull();
    }//GEN-LAST:event_menCadProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnBase;
    private javax.swing.JMenuBar Menu;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblPerfilUser;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadProd;
    public static javax.swing.JMenuItem menCadUserFull;
    private javax.swing.JMenu menHelp;
    private javax.swing.JMenuItem menHelpSobre;
    private javax.swing.JMenu menOption;
    private javax.swing.JMenuItem menOptionSair;
    // End of variables declaration//GEN-END:variables

    private void btnSairTelaPrincipal() {
        Object[] options = {"Sim", "Não"};
        int btnSair = JOptionPane.showOptionDialog(null, "Deseja realmente sair?", "Aviso",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (btnSair == 0) {
            System.exit(0);
        }
    }

    private void menuSobre() {
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
    }

    private void insereData() {
        Date data = new Date();
        DateFormat formata = DateFormat.getDateInstance(DateFormat.SHORT);
        //lblData.setText(data.toString()); //troca a "label Data" pela funcao date
        lblData.setText(formata.format(data)); //troca a "label Data" pela funcao date e formata
    }   
    
    private void menCadUserFull() {
        CadUser cadUserFull = new CadUser();
        cadUserFull.setVisible(true);
        desktop.add(cadUserFull);
    }    
   
    private void menCadProdFull() {
        CadProd cadProdFull = new CadProd();
        cadProdFull.setVisible(true);
        desktop.add(cadProdFull);
    }   
        
    //DIVERSOS
    //Insere o icone no form
    private void inserirIcon() {        
            URL localImagen = getClass().getResource("/image/BackgroundIcon48x48.png");
            Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(localImagen);
            this.setIconImage(iconeTitulo);        
    }
}